basic/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\data\Pagination;
use yii\helpers\html;
use yii\widgets\LinkPager;
use app\models\Mylist;
// use app\models\ContactForm;

class SiteController extends Controller
{
   

   

    public function actionIndex()
    {
        return $this->render('index');
    }


    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionHello()
    {
        $countresults = Mylist::getTotalProducts();
        $pagination = new Pagination([
            'defaultPageSize' => 10,
            'totalCount' => $countresults,
            ]);

        $filter_data = [
            'pagination' =>  $pagination,
        ];
        
        $results = Mylist::getAll($filter_data);

        foreach ($results as $result) {
            $data[] = array(
                'name' => $result['name'],
                'price' => $result['price'],
                'image' => $result['image'],
                'href' => 'two/'.$result['product_id'],
             );
        }

           //  echo "<pre>";
           // var_dump(Mylist::getTotalProducts());
           //  echo "</pre>";
       
        return $this->render('hello', [
            'results' => $data,
            'pagination' => LinkPager::widget(['pagination' => $pagination]),
            ]);
    }

    public function actionTwo($id)
    {

        $result = Mylist::getOne($id);

            $data = [
                'name' => $result['name'],
                'description' => html_entity_decode($result['description']),
                'model' => $result['model'],
                'qty' => $result['qty'],
                'price' => $result['price'],
                'image' => $result['image'],
            ];

        return $this->render('two', ['result' => $data]);
    }
}

basic/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
// echo "<pre>";
// var_dump($this);
// echo "</pre>";
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Hello', 'url' => ['/site/hello']],
            ['label' => 'Two', 'url' => ['/site/two']],
            
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>